image: alpine/edge
secrets:
  - e2e843cf-6f7e-4b74-989f-819a97ca70b8
sources:
  - git+ssh://git@git.sr.ht/~mattmundell/codemirror-ansi
tasks:
  - check: |
      cd codemirror-ansi
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
  - mirror: |
      cd codemirror-ansi
      git remote add github git@github.com:cookshack/codemirror-ansi.git
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      git push github main
